
 
 
 
 
 % Dish Type (Either Main, Snack, App., Drink)
 appetizers(arancini).
 appetizers(baquette_with_Spread).
 appetizers(bitterballen).
 appetizers(brie).
 appetizers(bruschetta).
 appetizers(caprese_Salad).
 appetizers(carpaccio).
 appetizers(ceviche).
 appetizers(charcuterie).
 appetizers(cheese_Fondue).
 appetizers(chips_and_Guacamole).
 appetizers(clam_Chowder).
 appetizers(dumplings).
 appetizers(empanadas).
 appetizers(escargot).
 appetizers(fajita).
 appetizers(fried_Plantains).
 appetizers(gazpacho).
 appetizers(gyoza).
 appetizers(lentil_Soup).
 appetizers(loempia).
 appetizers(meatballs).
 appetizers(miso_Soup).
 appetizers(nachos).
 appetizers(onigiri).
 appetizers(onion_soup).
 appetizers(papadam).
 appetizers(potatoes_Au_Gratin).
 appetizers(prosciutto_and_Melon).
 appetizers(quesadilla).
 appetizers(salad).
 appetizers(soup).
 appetizers(stuffed_Leaves).
 appetizers(temaki).
 appetizers(tteokbokki).
 dessert(baklava).
 dessert(banana_Split).
 dessert(bingsu).
 dessert(brownies).
 dessert(cheesecake).
 dessert(chocolate_Fondue).
 dessert(churros).
 dessert(cider_Donuts).
 dessert(creme_Brulee).
 dessert(cupcakes).
 dessert(dango).
 dessert(eclair).
 dessert(flan).
 dessert(fried_Dough).
 dessert(gelato).
 dessert(gulab_Jamun).
 dessert(ice_Cream).
 dessert(kaiserschmarrn).
 dessert(macaron).
 dessert(pie).
 dessert(profiteroles).
 dessert(pudding).
 dessert(rote_Grutze).
 dessert(sweet_Crepes).
 dessert(tiramisu).
 drink(ayran).
 drink(beer).
 drink(bellini).
 drink(bloody_Mary).
 drink(champagne).
 drink(cocktails).
 drink(cosmopolitan).
 drink(gluhwein).
 drink(mango_Lassi).
 drink(margarita).
 drink(martini).
 drink(mimosas).
 drink(mocktail).
 drink(mojito).
 drink(moscow_Mule).
 drink(open_Bar).
 drink(pina_Colada).
 drink(red_Wine).
 drink(sake).
 drink(sangria).
 drink(soda).
 drink(tea).
 drink(tequila).
 drink(tequila_Sunrise).
 drink(whiskey).
 drink(white_Wine).
 main_dish(bLT).
 main_dish(barbecue_Ribs).
 main_dish(bratwurst).
 main_dish(burger).
 main_dish(burrito).
 main_dish(butter_Chicken).
 main_dish(calzone).
 main_dish(caponata).
 main_dish(chili).
 main_dish(cordon_Bleu).
 main_dish(curry).
 main_dish(currywurst).
 main_dish(deep_Dish_Pizza).
 main_dish(donburi).
 main_dish(doner).
 main_dish(enchilladas).
 main_dish(fajita).
 main_dish(fondue).
 main_dish(fried_Chicken).
 main_dish(fried_Rice).
 main_dish(frikadellen).
 main_dish(gnocchi).
 main_dish(hot_Dogs).
 main_dish(hot_Pot).
 main_dish(japchae).
 main_dish(kasespatzle).
 main_dish(kebab).
 main_dish(lahmacun).
 main_dish(laksa).
 main_dish(lamb_Wrap).
 main_dish(lasagna).
 main_dish(lobster).
 main_dish(mac_and_Cheese).
 main_dish(manti).
 main_dish(maryland_Crabs).
 main_dish(matjes).
 main_dish(pad_Thai).
 main_dish(paella).
 main_dish(pizza).
 main_dish(quesadilla).
 main_dish(quiche_Lorraine).
 main_dish(ramen).
 main_dish(ratatouille).
 main_dish(ravioli).
 main_dish(risotto).
 main_dish(savory_Crepes).
 main_dish(schnitzel).
 main_dish(seafood_Jeon).
 main_dish(soba).
 main_dish(spaghetti_Bolognese).
 main_dish(steak).
 main_dish(sushi).
 main_dish(tacos).
 main_dish(tamales).
 main_dish(tandoori_Chicken).
 main_dish(tapas).
 main_dish(tonkatsu).
 main_dish(tortellini).
 main_dish(tteokbokki).
 main_dish(turkey).
 main_dish(udon).
 main_dish(vegetable_Curry).
 snacks(borek).
 snacks(buffalo_Wings).
 snacks(cheese_and_Crackers).
 snacks(chips).
 snacks(chips_and_Guacamole).
 snacks(corn_Dogs).
 snacks(falafel).
 snacks(fries).
 snacks(mince_Borek).
 snacks(naan).
 snacks(nachos).
 snacks(nutsmix).
 snacks(onion_Rings). snacks(popcorn).
 snacks(samosas).
 snacks(spinach_and_Feta_Borek).
 snacks(takoyaki).
 
 
 %
 %
 %
 %
 % Event type relations _ fancy, party, or get_together
 % appetizer(X) :- fancy(X)
 fancy(arancini).
 fancy(baklava).
 fancy(banana_Split).
 fancy(baquette_with_Spread).
 fancy(bellini).
 fancy(bingsu).
 fancy(bitterballen).
 fancy(brie).
 fancy(brownies).
 fancy(bruschetta).
 fancy(burrito).
 fancy(butter_Chicken).
 fancy(caprese_Salad).
 fancy(carpaccio).
 fancy(ceviche).
 fancy(champagne).
 fancy(charcuterie).
 fancy(cheese_Fondue).
 fancy(cheesecake).
 fancy(chili).
 fancy(chips_and_Guacamole).
 fancy(chocolate_Fondue).
 fancy(churros).
 fancy(cider_Donuts).
 fancy(clam_Chowder).
 fancy(cocktails).
 fancy(cordon_Bleu).
 fancy(cosmopolitan).
 fancy(creme_Brulee).
 fancy(cupcakes).
 fancy(dango).
 fancy(dumplings).
 fancy(eclair).
 fancy(empanadas).
 fancy(escargot).
 fancy(fajita).
 fancy(flan).
 fancy(fondue).
 fancy(fried_Dough).
 fancy(fried_Plantains).
 fancy(gazpacho).
 fancy(gelato).
 fancy(gnocchi).
 fancy(gulab_Jamun).
 fancy(gyoza).
 fancy(hot_Pot).
 fancy(ice_Cream).
 fancy(kaiserschmarrn).
 fancy(laksa).
 fancy(lasagna).
 fancy(lentil_Soup).
 fancy(lobster).
 fancy(loempia).
 fancy(macaron).
 fancy(manti).
 fancy(margarita).
 fancy(martini).
 fancy(maryland_Crabs).
 fancy(matjes).
 fancy(meatballs).
 fancy(mimosas).
 fancy(miso_Soup).
 fancy(moscow_Mule).
 fancy(onigiri).
 fancy(onion_soup).
 fancy(open_Bar).
 fancy(papadam).
 fancy(pie).
 fancy(potatoes_Au_Gratin).
 fancy(profiteroles).
 fancy(prosciutto_and_Melon).
 fancy(pudding).
 fancy(quesadilla).
 fancy(quiche_Lorraine).
 fancy(ratatouille).
 fancy(ravioli).
 fancy(red_Wine).
 fancy(rote_Grutze).
 fancy(sake).
 fancy(salad).
 fancy(savory_Crepes).
 fancy(soda).
 fancy(soup).
 fancy(steak).
 fancy(stuffed_Leaves).
 fancy(sushi).
 fancy(sweet_Crepes).
 fancy(tandoori_Chicken).
 fancy(temaki).
 fancy(tiramisu).
 fancy(tortellini).
 fancy(tteokbokki).
 fancy(turkey).
 fancy(udon).
 fancy(vegetable_Curry).
 fancy(whiskey).
 fancy(white_Wine).
 get_together(ayran).
 get_together(bLT).
 get_together(barbecue_Ribs).
 get_together(beer).
 get_together(bellini).
 get_together(bloody_Mary).
 get_together(bratwurst).
 get_together(buffalo_Wings).
 get_together(burger).
 get_together(burrito).
 get_together(butter_Chicken).
 get_together(calzone).
 get_together(caponata).
 get_together(chili).
 get_together(chips_and_Guacamole).
 get_together(cordon_Bleu).
 get_together(cosmopolitan).
 get_together(curry).
 get_together(deep_Dish_Pizza).
 get_together(donburi).
 get_together(doner).
 get_together(enchilladas).
 get_together(fajita).
 get_together(falafel).
 get_together(fried_Chicken).
 get_together(fries).
 get_together(frikadellen).
 get_together(gluhwein).
 get_together(gnocchi).
 get_together(hot_Dogs).
 get_together(hot_Pot).
 get_together(japchae).
 get_together(kasespatzle).
 get_together(kebab).
 get_together(lahmacun).
 get_together(laksa).
 get_together(lamb_Wrap).
 get_together(mac_and_Cheese).
 get_together(mango_Lassi).
 get_together(manti).
 get_together(margarita).
 get_together(mimosas).
 get_together(mince_Borek).
 get_together(mince_Borek).
 get_together(mocktail).
 get_together(mojito).
 get_together(naan).
 get_together(naan).
 get_together(nachos).
 get_together(onion_Rings).
 get_together(pad_Thai).
 get_together(paella).
 get_together(pina_Colada).
 get_together(quesadilla).
 get_together(quiche_Lorraine).
 get_together(ramen).
 get_together(ravioli).
 get_together(red_Wine).
 get_together(risotto).
 get_together(sake).
 get_together(samosas).
 get_together(samosas).
 get_together(sangria).
 get_together(schnitzel).
 get_together(seafood_Jeon).
 get_together(soba).
 get_together(soda).
 get_together(spaghetti_Bolognese).
 get_together(spinach_and_Feta_Borek).
 get_together(spinach_and_Feta_Borek).
 get_together(tacos).
 get_together(takoyaki).
 get_together(takoyaki).
 get_together(tamales).
 get_together(tandoori_Chicken).
 get_together(tea).
 get_together(tonkatsu).
 get_together(tortellini).
 get_together(tteokbokki).
 get_together(udon).
 get_together(vegetable_Curry).
 get_together(white_Wine).
 party(beer).
 party(borek).
 party(bratwurst).
 party(buffalo_Wings).
 party(champagne).
 party(cheese_and_Crackers).
 party(chips).
 party(cocktails).
 party(corn_Dogs).
 party(currywurst).
 party(fries).
 party(frikadellen).
 party(gluhwein).
 party(margarita).
 party(martini).
 party(mojito).
 party(moscow_Mule).
 party(nachos).
 party(nutsmix).
 party(onion_Rings).
 party(open_Bar).
 party(pina_Colada).
 party(pizza).
 party(popcorn).
 party(red_Wine).
 party(sake).
 party(sangria).
 party(sangria).
 party(stir_fry).
 party(tacos).
 party(tapas).
 party(tequila).
 party(tequila_Sunrise).
 party(white_Wine).
 
 
 
 
 
 
 % Season relations (winter includes fall, summer includes spring)
 both_seasons(arancini).
 both_seasons(bLT).
 both_seasons(baklava).
 both_seasons(baquette_with_Spread).
 both_seasons(beer).
 both_seasons(bellini).
 both_seasons(bitterballen).
 both_seasons(bloody_Mary).
 both_seasons(borek).
 both_seasons(bratwurst).
 both_seasons(brie).
 both_seasons(bruschetta).
 both_seasons(buffalo_Wings).
 both_seasons(burger).
 both_seasons(burrito).
 both_seasons(butter_Chicken).
 both_seasons(calzone).
 both_seasons(caponata).
 both_seasons(champagne).
 both_seasons(charcuterie).
 both_seasons(cheese_and_Crackers).
 both_seasons(chips).
 both_seasons(chips_and_Guacamole).
 both_seasons(chocolate_Fondue).
 both_seasons(churros).
 both_seasons(cider_Donuts).
 both_seasons(clam_Chowder).
 both_seasons(cocktails).
 both_seasons(cordon_Bleu).
 both_seasons(cosmopolitan).
 both_seasons(cupcakes).
 both_seasons(currywurst).
 both_seasons(dango).
 both_seasons(deep_Dish_Pizza).
 both_seasons(doner).
 both_seasons(dumplings).
 both_seasons(eclair).
 both_seasons(empanadas).
 both_seasons(escargot).
 both_seasons(falafel). both_seasons(flan).
 both_seasons(fried_Chicken).
 both_seasons(fried_Dough).
 both_seasons(fried_Rice).
 both_seasons(fries).
 both_seasons(frikadellen).
 both_seasons(gnocchi).
 both_seasons(gulab_Jamun).
 both_seasons(kaiserschmarrn).
 both_seasons(kebab).
 both_seasons(lahmacun).
 both_seasons(laksa).
 both_seasons(lamb_Wrap).
 both_seasons(loempia).
 both_seasons(mac_and_Cheese).
 both_seasons(macaron).
 both_seasons(mango_Lassi).
 both_seasons(manti).
 both_seasons(martini).
 both_seasons(meatballs).
 both_seasons(mimosas).
 both_seasons(mince_Borek).
 both_seasons(mince_Borek).
 both_seasons(mocktail).
 both_seasons(moscow_Mule).
 both_seasons(nachos).
 both_seasons(nachos).
 both_seasons(nutsmix).
 both_seasons(onigiri).
 both_seasons(onion_Rings).
 both_seasons(open_Bar).
 both_seasons(pad_Thai).
 both_seasons(papadam).
 both_seasons(pie).
 both_seasons(pizza).
 both_seasons(popcorn).
 both_seasons(potatoes_Au_Gratin).
 both_seasons(profiteroles).
 both_seasons(pudding).
 both_seasons(quesadilla).
 both_seasons(quesadilla).
 both_seasons(ravioli).
 both_seasons(rote_Grutze).
 both_seasons(sake).
 both_seasons(sangria).
 both_seasons(savory_Crepes).
 both_seasons(savory_Crepes).
 both_seasons(schnitzel).
 both_seasons(soda).
 both_seasons(spaghetti_Bolognese).
 both_seasons(spinach_and_Feta_Borek).
 both_seasons(spinach_and_Feta_Borek).
 both_seasons(steak).
 both_seasons(stuffed_Leaves).
 both_seasons(tacos).
 both_seasons(takoyaki).
 both_seasons(tamales).
 both_seasons(tequila).
 both_seasons(tiramisu).
 both_seasons(tonkatsu).
 both_seasons(tortellini).
 both_seasons(tteokbokki).
 both_seasons(udon).
 both_seasons(vegetable_Curry).
 both_seasons(whiskey).
 margarita(margarita).
 summer(X) :- both_seasons(X).
 summer(ayran).
 summer(banana_Split).
 summer(barbecue_Ribs).
 summer(bingsu).
 summer(caprese_Salad).
 summer(carpaccio).
 summer(ceviche).
 summer(cheesecake).
 summer(chips_and_Guacamole).
 summer(corn_Dogs).
 summer(donburi).
 summer(fried_Plantains).
 summer(gazpacho).
 summer(gelato).
 summer(hot_Dogs).
 summer(ice_Cream).
 summer(japchae).
 summer(lobster).
 summer(maryland_Crabs).
 summer(matjes).
 summer(mojito).
 summer(pina_Colada).
 summer(prosciutto_and_Melon).
 summer(ratatouille).
 summer(salad).
 summer(seafood_Jeon).
 summer(soba).
 summer(sushi).
 summer(tapas).
 summer(temaki).
 summer(tequila_Sunrise).
 summer(white_Wine).
 winter(X) :- both_seasons(X).
 winter(brownies).
 winter(cheese_Fondue).
 winter(chili).
 winter(creme_Brulee).
 winter(curry).
 winter(enchilladas).
 winter(fajita).
 winter(fondue).
 winter(gluhwein).
 winter(gyoza).
 winter(hot_Pot).
 winter(kasespatzle).
 winter(lasagna).
 winter(lentil_Soup).
 winter(miso_Soup).
 winter(naan).
 winter(onion_soup).
 winter(paella).
 winter(quiche_Lorraine).
 winter(ramen).
 winter(red_Wine).
 winter(risotto).
 winter(samosas).
 winter(soup).
 winter(tandoori_Chicken).
 winter(tea).
 winter(turkey).
 
 
 
 
 
 
 
 % Where relation
 anywhere(arancini).
 anywhere(ayran).
 anywhere(bLT).
 anywhere(baklava).
 anywhere(banana_Split).
 anywhere(baquette_with_Spread).
 anywhere(barbecue_Ribs).
 anywhere(beer).
 anywhere(bellini).
 anywhere(bingsu).
 anywhere(bitterballen).
 anywhere(bloody_Mary).
 anywhere(borek).
 anywhere(bratwurst).
 anywhere(brie).
 anywhere(brownies).
 anywhere(bruschetta).
 anywhere(buffalo_Wings).
 anywhere(burger).
 anywhere(burrito).
 anywhere(butter_Chicken).
 anywhere(caponata).
 anywhere(carpaccio).
 anywhere(champagne).
 anywhere(charcuterie).
 anywhere(cheese_and_Crackers).
 anywhere(cheesecake).
 anywhere(chips).
 anywhere(chips_and_Guacamole).
 anywhere(chips_and_Guacamole).
 anywhere(chocolate_Fondue).
 anywhere(churros).
 anywhere(cider_Donuts).
 anywhere(clam_Chowder).
 anywhere(cocktails).
 anywhere(cordon_Bleu).
 anywhere(corn_Dogs).
 anywhere(cosmopolitan).
 anywhere(creme_Brulee).
 anywhere(cupcakes).
 anywhere(currywurst).
 anywhere(dango).
 anywhere(deep_Dish_Pizza).
 anywhere(donburi).
 anywhere(doner).
 anywhere(dumplings).
 anywhere(eclair).
 anywhere(empanadas).
 anywhere(escargot).
 anywhere(falafel). anywhere(flan).
 anywhere(fried_Chicken).
 anywhere(fried_Dough).
 anywhere(fried_Rice).
 anywhere(fries).
 anywhere(frikadellen).
 anywhere(gazpacho).
 anywhere(gelato).
 anywhere(gluhwein).
 anywhere(gulab_Jamun).
 anywhere(gyoza).
 anywhere(hot_Dogs).
 anywhere(ice_Cream).
 anywhere(japchae).
 anywhere(kaiserschmarrn).
 anywhere(kasespatzle).
 anywhere(kebab).
 anywhere(lamb_Wrap).
 anywhere(lobster).
 anywhere(loempia).
 anywhere(mac_and_Cheese).
 anywhere(macaron).
 anywhere(mango_Lassi).
 anywhere(manti).
 anywhere(margarita).
 anywhere(martini).
 anywhere(maryland_Crabs).
 anywhere(matjes).
 anywhere(meatballs).
 anywhere(mimosas).
 anywhere(mince_Borek).
 anywhere(mince_Borek).
 anywhere(mocktail).
 anywhere(mojito).
 anywhere(moscow_Mule).
 anywhere(naan).
 anywhere(nachos).
 anywhere(nachos).
 anywhere(nutsmix).
 anywhere(onion_Rings).
 anywhere(onion_soup).
 anywhere(open_Bar).
 anywhere(paella).
 anywhere(papadam).
 anywhere(pie).
 anywhere(pina_Colada).
 anywhere(pizza).
 anywhere(popcorn).
 anywhere(potatoes_Au_Gratin).
 anywhere(profiteroles).
 anywhere(prosciutto_and_Melon).
 anywhere(pudding).
 anywhere(quesadilla).
 anywhere(quesadilla).
 anywhere(quiche_Lorraine).
 anywhere(ratatouille).
 anywhere(red_Wine).
 anywhere(rote_Grutze).
 anywhere(sake).
 anywhere(salad).
 anywhere(samosas).
 anywhere(sangria).
 anywhere(seafood_Jeon).
 anywhere(soba).
 anywhere(soda).
 anywhere(soup).
 anywhere(spaghetti_Bolognese).
 anywhere(spinach_and_Feta_Borek).
 anywhere(spinach_and_Feta_Borek).
 anywhere(stuffed_Leaves).
 anywhere(sushi).
 anywhere(sweet_Crepes).
 anywhere(tacos).
 anywhere(takoyaki).
 anywhere(tamales).
 anywhere(tandoori_Chicken).
 anywhere(tapas).
 anywhere(tea).
 anywhere(temaki).
 anywhere(tequila).
 anywhere(tequila_Sunrise).
 anywhere(tiramisu).
 anywhere(tonkatsu).
 anywhere(tteokbokki).
 anywhere(tteokbokki).
 anywhere(vegetable_Curry).
 anywhere(whiskey).
 anywhere(white_Wine).
 indoor(X)  :- anywhere(X).
 indoor(calzone).
 indoor(caprese_Salad).
 indoor(ceviche).
 indoor(cheese_Fondue).
 indoor(chili).
 indoor(curry).
 indoor(enchilladas).
 indoor(fajita).
 indoor(fondue).
 indoor(fried_Plantains).
 indoor(gnocchi).
 indoor(hot_Pot).
 indoor(lahmacun).
 indoor(laksa).
 indoor(lasagna).
 indoor(lentil_Soup).
 indoor(miso_Soup).
 indoor(onigiri).
 indoor(pad_Thai).
 indoor(ramen).
 indoor(ravioli).
 indoor(risotto).
 indoor(savory_Crepes).
 indoor(schnitzel).
 indoor(steak).
 indoor(tortellini).
 indoor(turkey).
 indoor(udon).
 outdoor(X) :- anywhere(X).
 
 
 
 %
 %
 %
 %
 % Time (lunch_dinner_night)
 all_meals(all_meals).
 all_meals(baklava).
 all_meals(banana_Split).
 all_meals(baquette_with_Spread).
 all_meals(beer).
 all_meals(bingsu).
 all_meals(borek).
 all_meals(brie).
 all_meals(brownies).
 all_meals(buffalo_Wings).
 all_meals(burrito).
 all_meals(caponata).
 all_meals(champagne).
 all_meals(charcuterie).
 all_meals(cheese_and_Crackers).
 all_meals(cheesecake).
 all_meals(chili).
 all_meals(chips).
 all_meals(chips_and_Guacamole).
 all_meals(chocolate_Fondue).
 all_meals(churros).
 all_meals(cider_Donuts).
 all_meals(cosmopolitan).
 all_meals(creme_Brulee).
 all_meals(cupcakes).
 all_meals(dango).
 all_meals(deep_Dish_Pizza).
 all_meals(donburi).
 all_meals(eclair).
 all_meals(falafel). all_meals(flan).
 all_meals(fried_Dough).
 all_meals(fried_Plantains).
 all_meals(fried_Rice).
 all_meals(fries).
 all_meals(gelato).
 all_meals(gulab_Jamun).
 all_meals(gyoza).
 all_meals(hot_Dogs).
 all_meals(hot_Pot).
 all_meals(ice_Cream).
 all_meals(japchae).
 all_meals(kaiserschmarrn).
 all_meals(kebab).
 all_meals(lahmacun).
 all_meals(laksa).
 all_meals(lamb_Wrap).
 all_meals(lentil_Soup).
 all_meals(mac_and_Cheese).
 all_meals(macaron).
 all_meals(manti).
 all_meals(mince_Borek).
 all_meals(miso_Soup).
 all_meals(mocktail).
 all_meals(naan).
 all_meals(nachos).
 all_meals(nachos).
 all_meals(nutsmix).
 all_meals(onion_Rings).
 all_meals(open_Bar).
 all_meals(pad_Thai).
 all_meals(pie).
 all_meals(pina_Colada).
 all_meals(pizza).
 all_meals(popcorn).
 all_meals(profiteroles).
 all_meals(prosciutto_and_Melon).
 all_meals(pudding).
 all_meals(quesadilla).
 all_meals(ramen).
 all_meals(ravioli).
 all_meals(rote_Grutze).
 all_meals(samosas).
 all_meals(sangria).
 all_meals(seafood_Jeon).
 all_meals(soba).
 all_meals(soda).
 all_meals(spinach_and_Feta_Borek).
 all_meals(stuffed_Leaves).
 all_meals(sushi).
 all_meals(sweet_Crepes).
 all_meals(takoyaki).
 all_meals(tamales).
 all_meals(temaki).
 all_meals(tiramisu).
 all_meals(tonkatsu).
 all_meals(tortellini).
 all_meals(white_Wine).
 dinner(X) :- all_meals(X).
 dinner(barbecue_Ribs).
 dinner(bellini).
 dinner(bitterballen).
 dinner(bratwurst).
 dinner(bruschetta).
 dinner(burger).
 dinner(butter_Chicken).
 dinner(carpaccio).
 dinner(ceviche).
 dinner(cheese_Fondue).
 dinner(clam_Chowder).
 dinner(cordon_Bleu).
 dinner(curry).
 dinner(dumplings).
 dinner(enchilladas).
 dinner(escargot).
 dinner(fajita).
 dinner(fondue).
 dinner(fried_Chicken).
 dinner(frikadellen).
 dinner(gazpacho).
 dinner(gluhwein).
 dinner(gnocchi).
 dinner(kasespatzle).
 dinner(lasagna).
 dinner(lobster).
 dinner(mango_Lassi).
 dinner(margarita).
 dinner(martini).
 dinner(maryland_Crabs).
 dinner(matjes).
 dinner(meatballs).
 dinner(mojito).
 dinner(moscow_Mule).
 dinner(onion_soup).
 dinner(paella).
 dinner(papadam).
 dinner(potatoes_Au_Gratin).
 dinner(quiche_Lorraine).
 dinner(ratatouille).
 dinner(red_Wine).
 dinner(risotto).
 dinner(sake).
 dinner(salad).
 dinner(savory_Crepes).
 dinner(schnitzel).
 dinner(soup).
 dinner(spaghetti_Bolognese).
 dinner(steak).
 dinner(tacos).
 dinner(tandoori_Chicken).
 dinner(tapas).
 dinner(turkey).
 dinner(udon).
 dinner(vegetable_Curry).
 dinner(whiskey).
 lunch(X)  :- all_meals(X).
 lunch(arancini).
 lunch(ayran).
 lunch(bLT).
 lunch(bellini).
 lunch(bitterballen).
 lunch(bloody_Mary).
 lunch(bratwurst).
 lunch(bruschetta).
 lunch(burger).
 lunch(butter_Chicken).
 lunch(calzone).
 lunch(caprese_Salad).
 lunch(chips_and_Guacamole).
 lunch(clam_Chowder).
 lunch(curry).
 lunch(currywurst).
 lunch(doner).
 lunch(dumplings).
 lunch(empanadas).
 lunch(fried_Chicken).
 lunch(frikadellen).
 lunch(gazpacho).
 lunch(kasespatzle).
 lunch(loempia).
 lunch(mango_Lassi).
 lunch(meatballs).
 lunch(mimosas).
 lunch(mince_Borek).
 lunch(onigiri).
 lunch(onion_soup).
 lunch(papadam).
 lunch(potatoes_Au_Gratin).
 lunch(quesadilla).
 lunch(quiche_Lorraine).
 lunch(ratatouille).
 lunch(risotto).
 lunch(salad).
 lunch(spaghetti_Bolognese).
 lunch(spinach_and_Feta_Borek).
 lunch(tacos).
 lunch(tandoori_Chicken).
 lunch(tea).
 lunch(tteokbokki).
 lunch(tteokbokki).
 lunch(vegetable_Curry).
 night(X)  :- all_meals(X).
 night(cocktails).
 night(margarita).
 night(martini).
 night(mojito).
 night(moscow_Mule).
 night(red_Wine).
 night(sake).
 night(tequila).
 night(tequila_Sunrise).
 night(whiskey).
 % Children existence relations
 children(ayran). children(bLT).
 children(baklava).
 children(banana_Split).
 children(baquette_with_Spread).
 children(barbecue_Ribs).
 children(bingsu).
 children(borek).
 children(bratwurst).
 children(brownies).
 children(buffalo_Wings).
 children(burger).
 children(burrito).
 children(butter_Chicken).
 children(cheese_and_Crackers).
 children(cheesecake).
 children(chips).
 children(chips_and_Guacamole).
 children(chocolate_Fondue).
 children(churros).
 children(cider_Donuts).
 children(clam_Chowder).
 children(cordon_Bleu).
 children(corn_Dogs).
 children(creme_Brulee).
 children(cupcakes).
 children(currywurst).
 children(dango).
 children(deep_Dish_Pizza).
 children(doner).
 children(dumplings).
 children(eclair).
 children(empanadas).
 children(enchilladas).
 children(fried_Chicken).
 children(fried_Dough).
 children(fried_Rice).
 children(fries).
 children(frikadellen).
 children(gelato).
 children(gyoza).
 children(hot_Dogs).
 children(ice_Cream).
 children(kaiserschmarrn).
 children(kasespatzle).
 children(kebab).
 children(lamb_Wrap).
 children(mac_and_Cheese).
 children(macaron).
 children(manti).
 children(meatballs).
 children(mince_Borek).
 children(mocktail).
 children(naan).
 children(nachos).
 children(nachos).
 children(nutsmix).
 children(onion_Rings).
 children(onion_soup).
 children(pad_Thai).
 children(pie).
 children(pizza).
 children(popcorn).
 children(potatoes_Au_Gratin).
 children(profiteroles).
 children(pudding).
 children(quesadilla).
 children(quiche_Lorraine).
 children(ravioli).
 children(rote_Grutze).
 children(savory_Crepes).
 children(schnitzel).
 children(soda).
 children(spaghetti_Bolognese).
 children(spinach_and_Feta_Borek).
 children(stuffed_Leaves).
 children(sweet_Crepes).
 children(tacos).
 children(temaki).
 children(tiramisu).
 children(tortellini).
 children(tteokbokki).
 
 
 
 
 
 
 
 
 % Vegan / Vegetarian / Dairy_free / nut allergy / none
 dairy(X)      :- appetizers(X).
 dairy(X)      :- drink(X), dif(X, mango_Lassi), dif(X, ayran).
 dairy(X)      :- snacks(X).
 dairy(baklava).
 dairy(baquette_with_Spread).
 dairy(barbecue_Ribs).
 dairy(bratwurst).
 dairy(buffalo_Wings).
 dairy(burger).
 dairy(ceviche).
 dairy(chili).
 dairy(curry).
 dairy(currywurst).
 dairy(donburi).
 dairy(fondue).
 dairy(fried_Rice).
 dairy(gazpacho).
 dairy(gyoza).
 dairy(hot_Dogs).
 dairy(hotpot).
 dairy(japchae).
 dairy(kebab).
 dairy(lahmacun).
 dairy(laksa).
 dairy(lamb_Wrap).
 dairy(lobster).
 dairy(manti).
 dairy(maryland_Crabs).
 dairy(mince_Borek).
 dairy(onigiri).
 dairy(pad_Thai).
 dairy(prosciutto_and_Melon).
 dairy(ramen).
 dairy(ratatouille).
 dairy(seafood_Jeon).
 dairy(spaghetti_Bolognese).
 dairy(steak).
 dairy(sushi).
 dairy(tacos).
 dairy(temaki).
 dairy(tonkatsu).
 dairy(turkey).
 dairy(vegetable_Curry).
 nuts(X)       :- appetizers(X).
 nuts(X)       :- dessert(X).
 nuts(X)       :- drink(X).
 nuts(X)       :- snacks(X), dif(X, nutsmix).
 nuts(bLT).
 nuts(banana_Split).
 nuts(baquette_with_Spread).
 nuts(barbecue_Ribs).
 nuts(bingsu).
 nuts(bratwurst).
 nuts(brie).
 nuts(buffalo_Wings).
 nuts(burger).
 nuts(burrito).
 nuts(butter_Chicken).
 nuts(calzone).
 nuts(chili).
 nuts(churros).
 nuts(cider_Donuts).
 nuts(clam_Chowder).
 nuts(cordon_Bleu).
 nuts(corn_Dogs).
 nuts(creme_Brulee).
 nuts(currywurst).
 nuts(dango).
 nuts(deep_Dish_Pizza).
 nuts(donburi).
 nuts(doner).
 nuts(eclair).
 nuts(fajita).
 nuts(flan).
 nuts(fried_Chicken).
 nuts(fried_Dough).
 nuts(fried_Rice).
 nuts(frikadellen).
 nuts(gazpacho).
 nuts(gelato).
 nuts(hot_Dogs).
 nuts(hotpot).
 nuts(japchae).
 nuts(kaiserschmarrn).
 nuts(kasespatzle).
 nuts(kebab).
 nuts(lahmacun).
 nuts(laksa).
 nuts(lobster).
 nuts(mac_and_Cheese).
 nuts(manti).
 nuts(maryland_Crabs).
 nuts(matjes).
 nuts(mince_Borek).
 nuts(onion_Rings).
 nuts(onion_soup).
 nuts(paella).
 nuts(pizza).
 nuts(potatoes_Au_Gratin).
 nuts(profiteroles).
 nuts(quesadilla).
 nuts(quiche_Lorraine).
 nuts(ratatouille).
 nuts(risotto).
 nuts(savory_Crepes).
 nuts(schnitzel).
 nuts(seafood_Jeon).
 nuts(spaghetti_Bolognese).
 nuts(steak).
 nuts(sweet_Crepes).
 nuts(tacos).
 nuts(tamales).
 nuts(tandoori_Chicken).
 nuts(tonkatsu).
 nuts(turkey).
 nuts(udon).
 vegan(X)      :- drink(X).
 vegan(bruschetta).
 vegan(caponata).
 vegan(cheese_and_Crackers).
 vegan(cupcakes).
 vegan(dango).
 vegan(falafel).
 vegan(fried_Plantains).
 vegan(gazpacho).
 vegan(gnocchi).
 vegan(lentil_soup).
 vegan(miso_Soup).
 vegan(nutsmix).
 vegan(popcorn).
 vegan(ratatouille).
 vegan(stuffed_Leaves).
 vegan(tacos).
 vegan(tteokbokki).
 vegan(udon).
 vegan(vegetable_Curry).
 vegetarian(X) :- drink(X).
 vegetarian(X) :- vegan(X).
 vegetarian(arancini).
 vegetarian(banana_Split).
 vegetarian(baquette_with_Spread).
 vegetarian(brie).
 vegetarian(brownies).
 vegetarian(caprese_Salad).
 vegetarian(cheesecake).
 vegetarian(chips).
 vegetarian(chips_and_Guacamole).
 vegetarian(churros).
 vegetarian(cider_Donuts).
 vegetarian(creme_Brulee).
 vegetarian(deep_Dish_Pizza).
 vegetarian(eclair).
 vegetarian(flan).
 vegetarian(fried_Dough).
 vegetarian(gazpacho).
 vegetarian(kaiserschmarrn).
 vegetarian(kasespatzle).
 vegetarian(mac_and_Cheese).
 vegetarian(macaron).
 vegetarian(nachos).
 vegetarian(nachos).
 vegetarian(onion_Rings).
 vegetarian(onion_soup).
 vegetarian(pizza).
 vegetarian(potatoes_Au_Gratin).
 vegetarian(profiteroles).
 vegetarian(ratatouille).
 vegetarian(ravioli).
 vegetarian(risotto).
 vegetarian(savory_Crepes).
 vegetarian(sweet_Crepes).
 vegetarian(tacos).
 vegetarian(tiramisu).
 vegetarian(vegetable_Curry).
 
 
 
 
 
 
 
 
 
 
 
 %
 % AMERICANS (N & S)
 % ASIA
 % Cuisine
 % EUROPE
 % american(X) :- any_cuisine(X).
 % asian(X)    :- any_cuisine(X).
 % french(X)   :- any_cuisine(X).
 % german(X)   :- american(X).
 % german(X)   :- any_cuisine(X).
 % indian(X)   :- any_cuisine(X).
 % italian(X)  :- any_cuisine(X).
 % italian(X)  :- spanish(X). 
 % japanese(X) :- any_cuisine(X).
 % mexican(X)  :- american(X). 
 % mexican(X)  :- any_cuisine(X).
 % spanish(X)  :- any_cuisine(X).
 % spanish(X)  :- italian(X). 
 % turkish(X)  :- any_cuisine(X).
 american(X) :- americans(X).
 american(bLT).
 american(banana_Split).
 american(barbecue_Ribs).
 american(bloody_Mary).
 american(brownies).
 american(buffalo_Wings).
 american(burger).
 american(champagne).
 american(cheese_and_Crackers).
 american(cheesecake).
 american(chips).
 american(chocolate_Fondue).
 american(cider_Donuts).
 american(clam_Chowder).
 american(corn_Dogs).
 american(cupcakes).
 american(deep_Dish_Pizza).
 american(fried_Chicken).
 american(fried_Dough).
 american(fries).
 american(hot_Dogs).
 american(lobster).
 american(mac_and_Cheese).
 american(martini).
 american(maryland_Crabs).
 american(mimosas).
 american(moscow_Mule).
 american(nutsmix).
 american(onion_Rings).
 american(popcorn).
 american(red_Wine).
 american(steak).
 american(turkey).
 americans(cosmopolitan).
 americans(ice_Cream).
 americans(mojito).
 americans(pie).
 americans(pudding).
 americans(whiskey).
 any_cuisine(beer).
 any_cuisine(cocktails).
 any_cuisine(mocktail).
 any_cuisine(open_Bar).
 any_cuisine(salad).
 any_cuisine(soda).
 any_cuisine(soup).
 any_cuisine(white_Wine).
 asian(X)    :- indian(X).
 asian(X)    :- japanese(X).
 asian(baklava).
 asian(bingsu).
 asian(curry).
 asian(dumplings).
 asian(fried_Rice).
 asian(hot_Pot).
 asian(japchae).
 asian(laksa).
 asian(loempia).
 asian(pad_Thai).
 asian(red_Wine).
 asian(seafood_Jeon).
 asian(tea).
 asian(tteokbokki).
 asian(tteokbokki).
 dutch(bitterballen).
 european(champagne).
 european(cheese_and_Crackers).
 european(cheesecake).
 european(chips).
 european(chocolate_Fondue).
 european(cosmopolitan).
 european(cupcakes).
 european(fries).
 european(ice_Cream).
 european(martini).
 european(mimosas).
 european(moscow_Mule).
 european(nutsmix).
 european(pie).
 european(popcorn).
 european(pudding).
 european(red_Wine).
 european(tea).
 european(whiskey).
 french(X) :- european(X).
 french(baquette_with_Spread).
 french(bloody_Mary).
 french(brie).
 french(champagne).
 french(charcuterie).
 french(cheese_Fondue).
 french(creme_Brulee).
 french(eclair).
 french(escargot).
 french(fondue).
 french(macaron).
 french(onion_soup).
 french(potatoes_Au_Gratin).
 french(profiteroles).
 french(quiche_Lorraine).
 french(ratatouille).
 french(savory_Crepes).
 french(sweet_Crepes).
 german(X) :- european(X).
 german(bratwurst).
 german(cordon_Bleu).
 german(currywurst).
 german(frikadellen).
 german(gluhwein).
 german(kaiserschmarrn).
 german(kasespatzle).
 german(matjes).
 german(rote_grutze).
 german(schnitzel).
 indian(butter_Chicken).
 indian(curry).
 indian(gulab_Jamun).
 indian(mango_Lassi).
 indian(naan).
 indian(papadam).
 indian(samosas).
 indian(tandoori_Chicken).
 indian(vegetable_Curry).
 italian(X) :- americans(X).
 italian(X) :- european(X).
 italian(arancini).
 italian(bellini).
 italian(bruschetta).
 italian(calzone).
 italian(caponata).
 italian(caprese_Salad).
 italian(carpaccio).
 italian(gelato).
 italian(gnocchi).
 italian(lasagna).
 italian(paella).
 italian(pizza).
 italian(prosciutto_and_Melon).
 italian(ravioli).
 italian(risotto).
 italian(spaghetti_Bolognese).
 italian(spaghetti_and_Meatballs).
 italian(tiramisu).
 italian(tortellini).
 japanese(dango).
 japanese(donburi).
 japanese(gyoza).
 japanese(miso_Soup).
 japanese(onigiri).
 japanese(ramen).
 japanese(sake).
 japanese(soba).
 japanese(sushi).
 japanese(takoyaki).
 japanese(temaki).
 japanese(tonkatsu).
 japanese(udon).
 mexican(X) :- americans(X).
 mexican(burrito).
 mexican(ceviche).
 mexican(chili).
 mexican(chips_and_Guacamole).
 mexican(empanadas).
 mexican(enchilladas).
 mexican(fajita).
 mexican(fried_Plantains).
 mexican(margarita).
 mexican(nachos).
 mexican(nachos).
 mexican(pina_Colada).
 mexican(quesadilla).
 mexican(quesadilla).
 mexican(tacos).
 mexican(tamales).
 mexican(tequila).
 mexican(tequila_Sunrise).
 spanish(X) :- americans(X).
 spanish(X) :- european(X).
 spanish(churros).
 spanish(flan).
 spanish(gazpacho).
 spanish(mojito).
 spanish(sangria).
 spanish(tapas).
 turkish(X) :- european(X).
 turkish(ayran).
 turkish(borek).
 turkish(doner).
 turkish(falafel). turkish(kebab).
 turkish(lahmacun).
 turkish(lamb_Wrap).
 turkish(lentil_Soup).
 turkish(manti).
 turkish(mince_Borek).
 turkish(spinach_and_Feta_Borek).
 turkish(stuffed_Leaves).
 