% Dish Type (Either Main, Snack, App., Drink)
main_dish(tacos).
main_dish(burger).
main_dish(risotto).
main_dish(curry).
main_dish(lobster).
main_dish(steak).
main_dish(lasagna).
main_dish(pizza).
main_dish(tapas).
main_dish(turkey).
main_dish(enchilladas).
main_dish(ramen).
main_dish(sushi).
main_dish(fondue).
main_dish(doner).
main_dish(pad_Thai).
main_dish(fried_Rice).
main_dish(schnitzel).
main_dish(currywurst).
main_dish(matjes).
main_dish(buffet).
main_dish(savory_Crepes).
main_dish(spaghetti_Bolognese).
main_dish(tandoori_Chicken).
main_dish(butter_Chicken).
main_dish(vegetable_Curry).
main_dish(gnocchi).
main_dish(ravioli).
main_dish(paella).
main_dish(tortellini).
main_dish(calzone).
main_dish(caponata).
main_dish(tamales).
main_dish(quesadilla).
main_dish(burrito).
main_dish(fajita).
main_dish(chili).
main_dish(udon).
main_dish(donburi).
main_dish(tonkatsu).
main_dish(soba).
main_dish(hot_Pot).
main_dish(japchae).
main_dish(laksa).
main_dish(tteokbokki).
main_dish(seafood_Jeon).
main_dish(manti).
main_dish(lahmacun).
main_dish(kebab).
main_dish(lamb_Wrap).
main_dish(kasespatzle).
main_dish(frikadellen).
main_dish(bratwurst).
main_dish(cordon_Bleu).
main_dish(quiche_Lorraine).
main_dish(ratatouille).
main_dish(mac_and_Cheese).
main_dish(hot_Dogs).
main_dish(fried_Chicken).
main_dish(barbecue_Ribs).
main_dish(maryland_Crabs).
main_dish(deep_Dish_Pizza).
main_dish(bLT).


drink(white_Wine).
drink(red_Wine).
drink(beer).
drink(soda).
drink(mocktail).
drink(cocktails).
drink(margarita).
drink(whiskey).
drink(mango_Lassi).
drink(gluhwein).
drink(champagne).
drink(mimosas).
drink(sake).
drink(mojito).
drink(martini).
drink(bloody_Mary).
drink(pina_Colada).
drink(open_Bar).
drink(bellini).
drink(cosmopolitan).
drink(moscow_Mule).
drink(tequila_Sunrise).
drink(tequila).
drink(sangria).
drink(ayran).
drink(tea).

appetizers(loempia).
appetizers(meatballs).
appetizers(bitterballen).
appetizers(bruschetta).
appetizers(dumplings).
appetizers(arancini).
appetizers(salad).
appetizers(soup).
appetizers(cheese_Fondue).
appetizers(papadam).
appetizers(carpaccio).
appetizers(escargot).
appetizers(charcuterie).
appetizers(nachos).
appetizers(fried_Plantains).
appetizers(caprese_Salad).
appetizers(prosciutto_and_Melon).
appetizers(quesadilla).
appetizers(empanadas).
appetizers(fajita).
appetizers(ceviche).
appetizers(chips_and_Guacamole).
appetizers(lentil_Soup).
appetizers(stuffed_Leaves).
appetizers(miso_Soup).
appetizers(onigiri).
appetizers(gyoza).
appetizers(temaki).
appetizers(tteokbokki).
appetizers(gazpacho).
appetizers(potatoes_Au_Gratin).
appetizers(onion_soup).
appetizers(baquette_with_Spread).
appetizers(brie).
appetizers(clam_Chowder).

dessert(tiramisu).
dessert(brownies).
dessert(baklava).
dessert(cheesecake).
dessert(cupcakes).
dessert(pudding).
dessert(ice_Cream).
dessert(pie).
dessert(gulab_Jamun).
dessert(chocolate_Fondue).
dessert(rote_Grutze).
dessert(sweet_Crepes).
dessert(kaiserschmarrn).
dessert(gelato).
dessert(bingsu).
dessert(dango).
dessert(flan).
dessert(churros).
dessert(creme_Brulee).
dessert(macaron).
dessert(eclair).
dessert(profiteroles).
dessert(banana_Split).
dessert(cider_Donuts).
dessert(fried_Dough).

snacks(chips).
snacks(cheese_and_Crackers).
snacks(nutsmix).
snacks(popcorn).
snacks(fries).
snacks(takoyaki).
snacks(naan).
snacks(borek).
snacks(samosas).
snacks(nachos).
snacks(chips_and_Guacamole).
snacks(mince_Borek).
snacks(spinach_and_Feta_Borek).
snacks(falafel).
snacks(buffalo_Wings).
snacks(corn_Dogs).
snacks(onion_Rings).