% Event type relations _ fancy, party, or get_together

get_together(tacos).
party(tacos).
get_together(enchilladas).
get_together(burger).
get_together(risotto).
get_together(curry).
fancy(lobster).
fancy(steak).
fancy(lasagna).
fancy(turkey).
party(pizza).
party(tapas).
get_together(ramen).
fancy(sushi).
fancy(fondue).
get_together(doner).
get_together(pad_Thai).
party(stir_fry).
get_together(schnitzel).
party(currywurst).
fancy(matjes).
fancy(savory_Crepes).
get_together(spaghetti_Bolognese).
get_together(tandoori_Chicken).
get_together(butter_Chicken).
get_together(vegetable_Curry).
fancy(tandoori_Chicken).
fancy(butter_Chicken).
fancy(vegetable_Curry).
get_together(kasespatzle).
get_together(frikadellen).
party(frikadellen).
get_together(bratwurst).
party(bratwurst).
fancy(cordon_Bleu).
get_together(cordon_Bleu).
get_together(gnocchi).
fancy(gnocchi).
get_together(ravioli).
fancy(ravioli).
get_together(paella).
get_together(tortellini).
fancy(tortellini).
get_together(calzone).
get_together(caponata).
get_together(tamales).
get_together(quesadilla).
get_together(burrito).
fancy(burrito).
get_together(fajita).
fancy(fajita).
get_together(chili).
fancy(chili).
get_together(udon).
fancy(udon).
get_together(donburi).
get_together(tonkatsu).
get_together(soba).
get_together(hot_Pot).
fancy(hot_Pot).
get_together(japchae).
get_together(laksa).
fancy(laksa).
get_together(tteokbokki).
get_together(seafood_Jeon).
get_together(manti).
fancy(manti).
get_together(lahmacun).
get_together(kebab).
get_together(mince_Borek).
get_together(spinach_and_Feta_Borek).
get_together(lamb_Wrap).
get_together(quiche_Lorraine).
fancy(quiche_Lorraine).
fancy(ratatouille).
get_together(mac_and_Cheese).
get_together(hot_Dogs).
get_together(fried_Chicken).
get_together(barbecue_Ribs).
fancy(maryland_Crabs).
get_together(deep_Dish_Pizza).
get_together(bLT).
%
fancy(red_Wine).
party(red_Wine).
get_together(red_Wine).
fancy(white_Wine).
party(white_Wine).
get_together(white_Wine).
get_together(beer).
party(beer).
get_together(soda).
fancy(soda).
get_together(mocktail).
fancy(cocktails).
party(cocktails).
fancy(whiskey).
party(margarita).
fancy(margarita).
get_together(margarita).
get_together(mango_Lassi).
get_together(gluhwein).
party(gluhwein).
fancy(champagne).
party(champagne).
fancy(mimosas).
get_together(mimosas).
get_together(sake).
party(sake).
fancy(sake).
party(mojito).
get_together(mojito).
fancy(martini).
party(martini).
get_together(bloody_Mary).
get_together(pina_Colada).
party(pina_Colada).
party(open_Bar).
fancy(open_Bar).
fancy(bellini).
get_together(bellini).
get_together(cosmopolitan).
fancy(cosmopolitan).
fancy(moscow_Mule).
party(moscow_Mule).
party(tequila_Sunrise).
party(tequila).
get_together(sangria).
party(sangria).
party(sangria).
get_together(tea).
get_together(ayran).
%
fancy(loempia).
fancy(meatballs).
fancy(bitterballen).
fancy(bruschetta).
fancy(dumplings).
fancy(arancini).
fancy(salad).
fancy(soup).
fancy(cheese_Fondue).
fancy(papadam).
fancy(carpaccio).
fancy(escargot).
fancy(charcuterie).
fancy(gazpacho).
fancy(fried_Plantains).
fancy(caprese_Salad).
fancy(prosciutto_and_Melon).
fancy(quesadilla).
fancy(empanadas).
fancy(ceviche).
fancy(chips_and_Guacamole).
fancy(lentil_Soup).
fancy(stuffed_Leaves).
fancy(miso_Soup).
fancy(onigiri).
fancy(gyoza).
fancy(temaki).
fancy(tteokbokki).
fancy(potatoes_Au_Gratin).
fancy(onion_soup).
fancy(baquette_with_Spread).
fancy(brie).
fancy(clam_Chowder).
% appetizer(X) :- fancy(X)

%
fancy(tiramisu).
fancy(brownies).
fancy(baklava).
fancy(cheesecake).
fancy(cupcakes).
fancy(pudding).
fancy(ice_Cream).
fancy(pie).
fancy(gulab_Jamun).
fancy(chocolate_Fondue).
fancy(rote_Grutze).
fancy(sweet_Crepes).
fancy(kaiserschmarrn).
fancy(flan).
fancy(churros).
fancy(creme_Brulee).
fancy(macaron).
fancy(eclair).
fancy(profiteroles).
fancy(gelato).
fancy(bingsu).
fancy(dango).
fancy(banana_Split).
fancy(cider_Donuts).
fancy(fried_Dough).
%
party(chips).
party(cheese_and_Crackers).
party(nutsmix).
party(popcorn).
party(fries).
get_together(fries).
get_together(takoyaki).
get_together(takoyaki).
get_together(naan).
get_together(naan).
party(borek).
get_together(samosas).
get_together(samosas).
get_together(nachos).
party(nachos).
get_together(chips_and_Guacamole).
get_together(mince_Borek).
get_together(spinach_and_Feta_Borek).
get_together(falafel).
get_together(buffalo_Wings).
party(buffalo_Wings).
party(corn_Dogs).
get_together(onion_Rings).
party(onion_Rings).
