% Season relations (winter includes fall, summer includes spring)

winter(X) :- both_seasons(X).
summer(X) :- both_seasons(X).

both_seasons(tacos).
both_seasons(burger).
winter(enchilladas).
winter(risotto).
winter(curry).
summer(lobster).
both_seasons(steak).
winter(lasagna).
winter(turkey).
both_seasons(pizza).
summer(tapas).
winter(ramen).
summer(sushi).
winter(fondue).
both_seasons(doner).
both_seasons(pad_Thai).
both_seasons(fried_Rice).
both_seasons(schnitzel).
both_seasons(currywurst).
summer(matjes).
both_seasons(buffet).
both_seasons(savory_Crepes).
both_seasons(spaghetti_Bolognese).
winter(tandoori_Chicken).
both_seasons(butter_Chicken).
both_seasons(vegetable_Curry).
winter(kasespatzle).
both_seasons(frikadellen).
both_seasons(bratwurst).
both_seasons(cordon_Bleu).
winter(quiche_Lorraine).
summer(ratatouille).
both_seasons(gnocchi).
both_seasons(ravioli).
winter(paella).
both_seasons(tortellini).
both_seasons(calzone).
both_seasons(caponata).
both_seasons(tamales).
both_seasons(quesadilla).
both_seasons(burrito).
winter(fajita).
winter(chili).
both_seasons(udon).
summer(donburi).
both_seasons(tonkatsu).
summer(soba).
winter(hot_Pot).
summer(japchae).
both_seasons(laksa).
both_seasons(tteokbokki).
summer(seafood_Jeon).
both_seasons(manti).
both_seasons(lahmacun).
both_seasons(kebab).
both_seasons(mince_Borek).
both_seasons(spinach_and_Feta_Borek).
both_seasons(lamb_Wrap).
both_seasons(mac_and_Cheese).
summer(hot_Dogs).
both_seasons(fried_Chicken).
summer(barbecue_Ribs).
summer(maryland_Crabs).
both_seasons(deep_Dish_Pizza).
both_seasons(bLT).

winter(red_Wine).
summer(white_Wine).
both_seasons(beer).
both_seasons(soda).
both_seasons(mocktail).
both_seasons(cocktails).
both_seasons(whiskey).
margarita(margarita).
both_seasons(mango_Lassi).
winter(gluhwein).
both_seasons(champagne).
both_seasons(mimosas).
both_seasons(sake).
summer(mojito).
both_seasons(martini).
both_seasons(bloody_Mary).
summer(pina_Colada).
both_seasons(open_Bar).
both_seasons(bellini).
both_seasons(cosmopolitan).
both_seasons(moscow_Mule).
summer(tequila_Sunrise).
both_seasons(tequila).
both_seasons(sangria).
winter(tea).
summer(ayran).

both_seasons(loempia).
both_seasons(meatballs).
both_seasons(bitterballen).
both_seasons(bruschetta).
both_seasons(dumplings).
both_seasons(arancini).
summer(salad).
winter(soup).
winter(cheese_Fondue).
both_seasons(papadam).
summer(carpaccio).
both_seasons(escargot).
both_seasons(charcuterie).
both_seasons(nachos).
summer(gazpacho).
both_seasons(potatoes_Au_Gratin).
winter(onion_soup).
both_seasons(baquette_with_Spread).
both_seasons(brie).
summer(fried_Plantains).
summer(caprese_Salad).
summer(prosciutto_and_Melon).
both_seasons(quesadilla).
both_seasons(empanadas).
summer(ceviche).
both_seasons(chips_and_Guacamole).
winter(lentil_Soup).
both_seasons(stuffed_Leaves).
winter(miso_Soup).
both_seasons(onigiri).
winter(gyoza).
summer(temaki).
both_seasons(clam_Chowder).

both_seasons(tiramisu).
winter(brownies).
both_seasons(baklava).
summer(cheesecake).
both_seasons(cupcakes).
both_seasons(pudding).
summer(ice_Cream).
both_seasons(pie).
both_seasons(gulab_Jamun).
both_seasons(chocolate_Fondue).
both_seasons(rote_Grutze).
both_seasons(savory_Crepes).
both_seasons(kaiserschmarrn).
both_seasons(flan).
both_seasons(churros).
winter(creme_Brulee).
both_seasons(macaron).
both_seasons(eclair).
both_seasons(profiteroles).
summer(banana_Split).
both_seasons(cider_Donuts).
both_seasons(fried_Dough).
summer(gelato).
summer(bingsu).
both_seasons(dango).

both_seasons(chips).
both_seasons(cheese_and_Crackers).
both_seasons(nutsmix).
both_seasons(popcorn).
both_seasons(fries).
both_seasons(takoyaki).
winter(naan).
both_seasons(borek).
winter(samosas).
both_seasons(buffalo_Wings).
summer(corn_Dogs).
both_seasons(onion_Rings).
both_seasons(nachos).
summer(chips_and_Guacamole).
both_seasons(mince_Borek).
both_seasons(spinach_and_Feta_Borek).
both_seasons(falafel).