% Time (lunch_dinner_night)

lunch(X)  :- all_meals(X).
dinner(X) :- all_meals(X).
night(X)  :- all_meals(X).

lunch(tacos).
dinner(tacos).
lunch(burger).
dinner(burger).
lunch(risotto).
dinner(risotto).
lunch(curry).
dinner(curry).
dinner(lobster).
dinner(steak).
dinner(lasagna).
dinner(turkey).
all_meals(pizza).
dinner(tapas).
dinner(enchilladas).
all_meals(ramen).
all_meals(sushi).
dinner(fondue).
lunch(doner).
all_meals(pad_Thai).
all_meals(fried_Rice).
dinner(schnitzel).
lunch(currywurst).
dinner(matjes).
all_meals(buffet).
dinner(savory_Crepes).
lunch(spaghetti_Bolognese).
dinner(spaghetti_Bolognese).
lunch(tandoori_Chicken).
lunch(butter_Chicken).
lunch(vegetable_Curry).
dinner(tandoori_Chicken).
dinner(butter_Chicken).
dinner(vegetable_Curry).
lunch(kasespatzle).
dinner(kasespatzle).
lunch(frikadellen).
dinner(frikadellen).
lunch(bratwurst).
dinner(bratwurst).
dinner(cordon_Bleu).
lunch(quiche_Lorraine).
dinner(quiche_Lorraine).
lunch(ratatouille).
dinner(ratatouille).
all_meals(mac_and_Cheese).
all_meals(hot_Dogs).
lunch(fried_Chicken).
dinner(fried_Chicken).
dinner(barbecue_Ribs).
dinner(maryland_Crabs).
all_meals(deep_Dish_Pizza).
lunch(bLT).
dinner(gnocchi).
all_meals(ravioli).
dinner(paella).
all_meals(tortellini).
lunch(calzone).
all_meals(caponata).
all_meals(tamales).
all_meals(quesadilla).
all_meals(burrito).
dinner(fajita).
all_meals(chili).
dinner(udon).
all_meals(donburi).
all_meals(tonkatsu).
all_meals(soba).
all_meals(hot_Pot).
all_meals(japchae).
all_meals(laksa).
lunch(tteokbokki).
all_meals(seafood_Jeon).
all_meals(manti).
all_meals(lahmacun).
all_meals(kebab).
lunch(mince_Borek).
lunch(spinach_and_Feta_Borek).
all_meals(lamb_Wrap).
%
dinner(red_Wine).
night(red_Wine).
all_meals(white_Wine).
all_meals(beer).
all_meals(soda).
all_meals(mocktail).
night(cocktails).
dinner(whiskey).
night(whiskey).
dinner(margarita).
night(margarita).
lunch(mango_Lassi).
dinner(mango_Lassi).
dinner(gluhwein).
all_meals(champagne).
lunch(mimosas).
dinner(sake).
night(sake).
dinner(mojito).
night(mojito).
dinner(martini).
night(martini).
lunch(bloody_Mary).
all_meals(pina_Colada).
all_meals(open_Bar).
lunch(bellini).
dinner(bellini).
all_meals(cosmopolitan).
dinner(moscow_Mule).
night(moscow_Mule).
night(tequila_Sunrise).
night(tequila).
all_meals(sangria).
lunch(tea).
lunch(ayran).
%
lunch(loempia).
lunch(meatballs).
dinner(meatballs).
lunch(bitterballen).
dinner(bitterballen).
lunch(bruschetta).
dinner(bruschetta).
lunch(dumplings).
dinner(dumplings).
lunch(arancini).
lunch(salad).
dinner(salad).
dinner(soup).
dinner(cheese_Fondue).
lunch(papadam).
dinner(papadam).
dinner(carpaccio).
dinner(escargot).
all_meals(charcuterie).
all_meals(nachos).
lunch(gazpacho).
dinner(gazpacho).
lunch(potatoes_Au_Gratin).
dinner(potatoes_Au_Gratin).
lunch(onion_soup).
dinner(onion_soup).
all_meals(baquette_with_Spread).
all_meals(brie).
lunch(clam_Chowder).
dinner(clam_Chowder).

all_meals(fried_Plantains).
lunch(caprese_Salad).
all_meals(prosciutto_and_Melon).
lunch(quesadilla).
lunch(empanadas).
dinner(ceviche).
lunch(chips_and_Guacamole).
all_meals(lentil_Soup).
all_meals(stuffed_Leaves).
all_meals(miso_Soup).
lunch(onigiri).
all_meals(gyoza).
all_meals(temaki).
lunch(tteokbokki).
%
all_meals(tiramisu).
all_meals(brownies).
all_meals(baklava).
all_meals(cheesecake).
all_meals(cupcakes).
all_meals(pudding).
all_meals(ice_Cream).
all_meals(pie).
all_meals(gulab_Jamun).
all_meals(chocolate_Fondue).
all_meals(rote_Grutze).
all_meals(sweet_Crepes).
all_meals(kaiserschmarrn).
all_meals(flan).
all_meals(churros).
all_meals(creme_Brulee).
all_meals(macaron).
all_meals(eclair).
all_meals(profiteroles).
all_meals(banana_Split).
all_meals(cider_Donuts).
all_meals(fried_Dough).
all_meals(gelato).
all_meals(bingsu).
all_meals(dango).
%
all_meals(chips).
all_meals(cheese_and_Crackers).
all_meals(nutsmix).
all_meals(popcorn).
all_meals(fries).
all_meals(takoyaki).
all_meals(naan).
all_meals(borek).
all_meals(samosas).
all_meals(buffalo_Wings).
all_meals(all_meals).
all_meals(onion_Rings).
all_meals(nachos).
all_meals(chips_and_Guacamole).
all_meals(mince_Borek).
all_meals(spinach_and_Feta_Borek).
all_meals(falafel).