% Where relation

:- discontiguous indoor/1.
:- discontiguous anywhere/1.
:- discontiguous outdoor/1.

% outdoor(X) :- anywhere(X).
% indoor(X)  :- anywhere(X).

anywhere(tacos).
anywhere(burger).
indoor(risotto).
indoor(curry).
indoor(chicken).
anywhere(lobster).
indoor(steak).
indoor(lasagna).
indoor(turkey).
anywhere(pizza).
anywhere(tapas).
indoor(enchilladas).
indoor(ramen).
anywhere(sushi).
indoor(fondue).
anywhere(doner).
indoor(pad_Thai).
anywhere(fried_Rice).
indoor(schnitzel).
anywhere(currywurst).
anywhere(matjes).
anywhere(buffet).
indoor(savory_Crepes).
anywhere(spaghetti_Bolognese).
anywhere(tandoori_Chicken).
anywhere(butter_Chicken).
anywhere(vegetable_Curry).
anywhere(kasespatzle).
anywhere(frikadellen).
anywhere(bratwurst).
anywhere(cordon_Bleu).
anywhere(quiche_Lorraine).
anywhere(ratatouille).
anywhere(mac_and_Cheese).
anywhere(hot_Dogs).
anywhere(fried_Chicken).
anywhere(barbecue_Ribs).
anywhere(maryland_Crabs).
anywhere(deep_Dish_Pizza).
anywhere(blt).
indoor(gnocchi).
indoor(ravioli).
anywhere(paella).
indoor(tortellini).
indoor(calzone).
anywhere(caponata).
anywhere(tamales).
anywhere(quesadilla).
anywhere(burrito).
indoor(fajita).
indoor(chili).
indoor(udon).
anywhere(donburi).
anywhere(tonkatsu).
anywhere(soba).
indoor(hot_Pot).
anywhere(japchae).
indoor(laksa).
anywhere(tteokbokki).
anywhere(seafood_Jeon).
anywhere(manti).
indoor(lahmacun).
anywhere(kebab).
anywhere(mince_Borek).
anywhere(spinach_and_Feta_Borek).
anywhere(lamb_Wrap).

anywhere(wine).
anywhere(beer).
anywhere(soda).
anywhere(mocktail).
anywhere(cocktails).
anywhere(whiskey).
anywhere(margarita).
anywhere(mango_Lassi).
anywhere(gluhwein).
anywhere(champagne).
anywhere(mimosas).
anywhere(sake).
anywhere(mojito).
anywhere(martini).
anywhere(bloody_Mary).
anywhere(pina_Colada).
anywhere(open_Bar).
anywhere(bellini).
anywhere(cosmopolitan).
anywhere(moscow_Mule).
anywhere(tequila_Sunrise).
anywhere(tequila).
anywhere(sangria).

anywhere(loempia).
anywhere(meatballs).
anywhere(bitterballen).
anywhere(bruschetta).
anywhere(dumplings).
anywhere(arancini).
anywhere(salad).
anywhere(soup).
indoor(cheese_Fondue).
anywhere(papadam).
anywhere(carpaccio).
anywhere(escargot).
anywhere(charcuterie).
anywhere(nachos).
anywhere(gazpacho).
anywhere(potatoes_Au_Gratin).
anywhere(onion_soup).
anywhere(baquette_with_Spread).
anywhere(brie).
anywhere(clam_Chowder).

indoor(fried_Plantains).
indoor(caprese_Salad).
anywhere(prosciutto_and_Melon).
anywhere(quesadilla).
anywhere(empanadas).
indoor(ceviche).
anywhere(chips_and_Guacamole).
indoor(lentil_Soup).
anywhere(stuffed_Leaves).
indoor(miso_Soup).
indoor(onigiri).
anywhere(gyoza).
anywhere(temaki).
anywhere(tteokbokki).

anywhere(tiramisu).
anywhere(brownies).
anywhere(baklava).
anywhere(cheesecake).
anywhere(cupcakes).
anywhere(pudding).
anywhere(ice_Cream).
anywhere(pie).
anywhere(gulab_Jamun).
anywhere(chocolate_Fondue).
anywhere(rote_Grutze).
anywhere(sweet_Crepes).
anywhere(kaiserschmarrn).
anywhere(flan).
anywhere(churros).
anywhere(creme_Brulee).
anywhere(macaron).
anywhere(eclair).
anywhere(profiteroles).
anywhere(banana_Split).
anywhere(cider_Donuts).
anywhere(fried_Dough).
anywhere(gelato).
anywhere(bingsu).
anywhere(dango).

anywhere(chips).
anywhere(crackers).
anywhere(peanuts).
anywhere(nutsmix).
anywhere(popcorn).
anywhere(fries).
anywhere(takoyaki).
anywhere(naan).
anywhere(borek).
anywhere(samosas).
anywhere(buffalo_Wings).
anywhere(corn_Dogs).
anywhere(onion_Rings).
anywhere(nachos).
anywhere(chips_and_Guacamole).
anywhere(mince_Borek).
anywhere(spinach_and_Feta_Borek).
anywhere(falafel).